// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnjtgjakakilxiglwztm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuanRnamFrYWtpbHhpZ2x3enRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzgzMTUsImV4cCI6MjA3MDc1NDMxNX0.EHRkb6Koz_ZKqpu_AyETY1fvc33asa7SrXNHANXGWzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});